#---- Directory structure config ----
sample_dir: "samples"
out_dir: "results"
fastqc_dir: "fastqc"
filtered_read_dir: "reads/filtered"
kmer_dir: "kmer"
alignment_dir: "alignment"
snpcall_dir: "snpcall"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
conda_config: "envs/conda.yaml"
#---- Tool threads ----
# tune alignment threads
fastqc_threads: 2
trimmomatic_threads: 10
bwa_threads: 19
sort_threads: 5
markdup_threads: 2
fixmate_threads: 1
index_threads: 5
mosdepth_threads: 10
baserecalibrator_threads: 1
applybsqr_threads: 1
#---- Tool memory ---- #TODO: adjust memory requirements
fastqc_mem_mb: 10000
trimmomatic_mem_mb: 10000
mosdepth_mem_mb: 4000 #The amount of memory is approximately equal to 32-bits * longest chrom length, so for the 249MB chromosome 1, it will require 1GB of memory.
index_mem_mb: 10000
bwa_mem_mb: 20000
fixmate_mem_mb: 5000
markdup_mem_mb: 5000
per_thread_sort_mem: 10 # memory in gigabytes TODO: adjust on cluster !!!!lowered for testing
baserecalibrator_mem_mb:  # TODO: add
applybsqr_mem_mb: # TODO: add
#---- Tool time ----
fastqc_time: "04:00:00"
trimmomatic_time: "10:00:00"
mosdepth_time: "10:00:00"
index_time: "10:00:00"
map_time: "48:00:00"
baserecalibrator_time: "24:00:00"
applybsqr_time: "24:00:00"
#---- Tool variables ----
trimmomatic_adapters:   #SET!!!!!!!!!!!!!!
reference:              #SET!!!!!!!!!!
mosdpth_min_mapping_quality: 20
#---- Cluster config ----
#template:
#  account: account,
#  time: "00:15:00",
#  n: 1,
#  partition : core