#---- Directory structure config ----
sample_dir: "samples"
out_dir: "results"
fastqc_dir: "fastqc"
filtered_read_dir: "reads/filtered"
kmer_dir: "kmer"
alignment_dir: "alignment"
snpcall_dir: "snpcall"
joint_snpcall_dir: "joint_snpcall"
log_dir: "logs"
cluster_log_dir: "cluster_logs"
error_dir: "errors"
benchmark_dir: "benchmarks"
conda_config: "envs/conda.yaml"
known_variants_dir: "resources/known_variants"
#---- Vcfs with known variants ----
mills_vcf: "Mills_and_1000G_gold_standard.indels.hg38.vcf.gz"
axiompoly_vcf: "Axiom_Exome_Plus.genotypes.all_populations.poly.hg38.vcf.gz"
dbsnp_vcf: "Homo_sapiens_assembly38.dbsnp138.vcf"
hapmap_vcf: "hapmap_3.3.hg38.vcf.gz"
omni_vcf: "1000G_omni2.5.hg38.vcf.gz"
g1000_vcf: "1000G_phase1.snps.high_confidence.hg38.vcf.gz"
#---- Tool threads ----
faidx_threads: 1
dict_threads: 1
prepare_recalibration_regions_threads: 1
prepare_genotyping_whitelist_intervals_threads: 1
fastqc_threads: 2
trimmomatic_threads: 10
bwa_threads: 19
sort_threads: 5
markdup_threads: 2
fixmate_threads: 1
index_threads: 5
mosdepth_threads: 10
jellyfish_count_threads: 26
jellyfish_histo_threads: 10
baserecalibrator_threads: 1
gatherbsqrreports_threads: 1
applybsqr_threads: 1
haplotypecaller_threads: 2
merge_splited_gvcf_threads: 1
index_merged_gvcf_threads: 1
genomicsdbimport_interval_threads: 13
genomicsdbimport_reader_threads: 13
genotypegvcfs_threads: 1
excess_filter_threads: 1
extract_sites_threads: 1
variantrecalibrator_indel_threads: 1
variantrecalibrator_snp_threads: 1
applyvsqr_indel_threads: 1
applyvsqr_snp_threads: 1
variantcalling_metrics_threads: 1
varianteval_metrics_threads: 1
select_good_variants_threads: 2
select_per_sample_variants_threads: 1
#---- Tool memory ---- #TODO: adjust memory requirements
faidx_mem_mb: 1000
dict_mem_mb: 1000
prepare_recalibration_regions_mem_mb: 100
prepare_genotyping_whitelist_intervals_mem_mb: 100
fastqc_mem_mb: 2000
trimmomatic_mem_mb: 10000
mosdepth_mem_mb: 4000 #The amount of memory is approximately equal to 32-bits * longest chrom length, so for the 249MB chromosome 1, it will require 1GB of memory.
jellyfish_count_mem_mb: 189440 # 185 Gb
jellyfish_histo_mem_mb: 10240 # 10Gb
index_mem_mb: 10000
bwa_mem_mb: 30000
fixmate_mem_mb: 20000
markdup_mem_mb: 20000
per_thread_sort_mem: 10 # memory in gigabytes
baserecalibrator_mem_mb:  20000 #
gatherbsqrreports_mem_mb: 6000
applybsqr_mem_mb: 40000 #
haplotypecaller_mem_mb: 20000 #
merge_splited_gvcf_mem_mb: 10000
index_merged_gvcf_mem_mb: 10000
genomicsdbimport_mem_mb: 50000
genotypegvcfs_mem_mb: 50000
excess_filter_mem_mb: 10000
extract_sites_mem_mb: 5000
variantrecalibrator_indel_mem_mb: 100000
variantrecalibrator_snp_mem_mb: 100000
applyvsqr_indel_mem_mb: 100000
applyvsqr_snp_mem_mb: 100000
variantcalling_metrics_mem_mb: 10000
varianteval_metrics_mem_mb: 10000
select_good_variants_mem_mb: 10000
select_per_sample_variants_mem_mb: 10000
#---- Tool time ----
faidx_time: "00:30:00"
dict_time: "00:30:00"
fastqc_time: "04:00:00"
trimmomatic_time: "10:00:00"
mosdepth_time: "10:00:00"
index_time: "10:00:00"
map_time: "48:00:00"
jellyfish_count_time: "12:00:00"
jellyfish_histo_time: "10:00:00"
prepare_recalibration_regions_time: "00:10:00"
prepare_genotyping_whitelist_intervals_time: "00:10:00"
baserecalibrator_time: "2:00:00"
gatherbsqrreports_time: "2:00:00"
applybsqr_time: "24:00:00"
haplotypecaller_time: "10:00:00"
merge_splited_gvcf_time: "02:00:00"
index_merged_gvcf_time: "02:00:00"
genomicsdbimport_time: "12:00:00"
genotypegvcfs_time: "24:00:00"
excess_filter_time: "05:00:00"
extract_sites_time: "01:00:00"
variantrecalibrator_indel_time: "48:00:00"
variantrecalibrator_snp_time: "48:00:00"
applyvsqr_indel_time: "48:00:00"
applyvsqr_snp_time: "48:00:00"
variantcalling_metrics_time: "05:00:00"
varianteval_metrics_time: "05:00:00"
select_good_variants_time: "05:00:00"
select_per_sample_variants_time: "05:00:00"
#---- Tool variables ----
trimmomatic_adapters: "resources/adapters/TruSeq2-PE.fa"
reference:              #SET!!!!!!!!!!
mosdepth_min_mapping_quality: 20
jellyfish_kmer_length: 23
split_regions_max_region_length: 25000000
split_regions_max_seq_number: 100
split_regions_region_file_format: "GATK"
split_regions_min_scaffold_length: 1
#split_regions_scaffold_whitelist: ""
#split_regions_scaffold_blacklist: ""
